spring:
    application:
        name: StartPoint-was

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:test}
        username: ${DATABASE_USER:root}
        password: ${DATABASE_PASS:password}
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            password: ${REDIS_PASSWORD:}
            database: ${REDIS_DB:0}
    jackson:
        time-zone: Asia/Seoul
        serialization:
            write-dates-as-timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            chat:
                options:
                    model: gpt-3.5-turbo

logging:
    level:
        org.springframework.ai.chat.client.advisor: DEBUG

