spring:
    application:
        name: StartPoint-was

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
        username: JHEEE116
        password: yt1357#1
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            password: ${REDIS_PASSWORD:}
            database: ${REDIS_DB:0}
    jackson:
        time-zone: Asia/Seoul
        serialization:
            write-dates-as-timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            chat:
                options:
                    model: gpt-3.5-turbo
    main:
        allow-bean-definition-overriding: true

logging:
    level:
        org.springframework.ai.chat.client.advisor: DEBUG


