name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/likelion-yeungnam-univ/startpoint-was:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE }}
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          GHCR_USER: ${{ github.actor }}
          GHCR_PAT: ${{ secrets.CR_PAT }}
          IMAGE: ${{ env.IMAGE }}
          NAME: startpoint-was
          HOST_PORT: 80
          APP_PORT: 8080
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull "$IMAGE"
          docker stop "$NAME" || true
          docker rm "$NAME" || true
          docker run -d --name "$NAME" -p $HOST_PORT:$APP_PORT "$IMAGE"
          EOF